export const Links = [
    { title: 'Importancia del archivo robots.txt para la seguridad y el seo', url:'/importancia'},
    { title: 'Optimización interna de una pagina web', url:'/optimizacion-interna'},
    { title: 'Dónde se inserta el código de Google Analytics en Joomla! 2.5', url:'/donde'},
    { title: 'htaccess en joomla!', url:'/htaccess'},
    { title: 'Las directrices para webmaster de Google', url:'/las-directories'},
    { title: 'Como construir un cotizador, calculadora o formula en joomla', url:'/joomla'},
    { title: 'Como encontrar HTTP Error 500 en joomla!', url:'/joomla'},
    { title: 'Inline small CSS', url:'/seo'},
    { title: 'Causesa de disminucion de visitas o trafico web', url:'/causesa'},
    { title: 'Que aspectos considerar en e-commerce para garantizar su exito', url:'/e-commerce'},
    { title: 'Como quitar la advertencia de malware por parte de Google', url:'/seguridad'},
    { title: 'Enlaces negativos: Como afectan su sitio y su marca', url:'/seguridad'},
    { title: 'Tutorial SEO Optimización Para Motores de Búsqueda', url:'/seguridad'},
    { title: 'Como agregar encabezados Expires', url:'/seguridad'},
    { title: 'Que significa Minify CSS', url:'/seguridad'},
    { title: 'Como las páginas en cache optimizan el rendimiento del sitio', url:'/seguridad'},
    { title: 'Como especificar dimensiones de imagen.', url:'/seguridad'},
    { title: '>Que características debe tener una contraseña para que sea segura en Joomla', url:'/seguridad'},
    { title: 'Qué hacer si recibe una acción manual contra spam', url:'/seguridad'},
    { title: 'Configuracion seo en Joomla', url:'/seguridad'},
    { title: 'Enlaces pagados y publicidad', url:'/seguridad'},
    { title: 'Recursos bloqueados Herramientas Para Webmaster de Google', url:'/seguridad'},
    { title: 'Redireccionamientos engañosos', url:'/seguridad'},
    { title: 'Tutorial permisos correctos de archivos y carpetas joomla', url:'/seguridad'},
    { title: 'Porque minimizar redirecciones', url:'/seguridad'},
    { title: 'Importancia de las copias de seguridad', url:'/seguridad'},
    { title: 'Como crear una pagina personalizada 404 en joomla', url:'/seguridad'},
    { title: 'Importancia de usar un nombre de usuario y contraseña fuerte', url:'/seguridad'},
    { title: 'Como usar el atributo alias en joomla', url:'/seguridad'},
    { title: 'Como afecta el número de página indexadas la clasificación de su sitio', url:'/seguridad'},
    { title: 'Como Configurar Herramientas para Webmasters de Google', url:'/seguridad'},
    { title: 'Por que son malos los enlaces rotos', url:'/seguridad'},
    { title: 'Cómo quitar los enlaces ocultos de las plantillas Joomla', url:'/seguridad'},
    { title: 'problemas de seguridad de Joomla', url:'/seguridad'},
    { title: 'Como proteger un directorio usando cpanel', url:'/seguridad'},
    { title: '¿Cómo puedo saber si mi sitio está infectado?', url:'/seguridad'},
    { title: 'Joomla contenido duplicado', url:'/seguridad'},
    { title: 'Como Probar el Archivo robots.txt', url:'/seguridad'},
    { title: 'Tutorial como crear una plantilla joomla básica', url:'/seguridad'},
    { title: 'Porque Mi Sitio No Aparece en los Resultados de Búsqueda', url:'/seguridad'},
    { title: 'Procedimientos de Seguridad Recomendados', url:'/seguridad'},
    { title: 'Procesar paginas con explorar como Google', url:'/seguridad'},
    { title: 'Cómo optimizar el contenido multimedia para SEO', url:'/seguridad'},
    { title: 'Importancia Palabras Clave de Contenido para Seo', url:'/seguridad'},
    { title: 'Cómo Recuperarse del Efecto Google Panda', url:'/seguridad'},
    { title: 'Proteja su sitio contra ataques de fuerza bruta', url:'/seguridad'},
    { title: 'Proteja su sitio contra ataques de fuerza bruta', url:'/seguridad'},
    { title: 'Proteja su sitio contra ataques de fuerza bruta', url:'/seguridad'},
    { title: 'Como proteger su contenido', url:'/seguridad'},
    { title: 'Las Vulnerabilidades Lógicas', url:'/seguridad'},
    { title: 'Cómo crear un mapa del sitio', url:'/seguridad'},
    { title: 'Por que Disminuyen las Paginas Indexadas en Mi Sitemap.xml', url:'/seguridad'}
]
